name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        run: dotnet publish TNRelay/TNRelay.csproj -c Release -o /home/tzer0m/Services/TNRelay
